---
- name: a10
  hosts: a10
  connection: local
  tasks:
  - name: server
    a10_server_axapi3:
     validate_certs: false
     host: "{{ inventory_hostname }}"
     username: ugil
     password: q1w2e3r4
     server: r192_9
     server_ip: 192.168.1.9
     server_status: enable
     write_config: yes
     use_proxy: no
     server_ports:
      - port-number: 8080
        protocol: tcp
        action: enable
