---
- hosts: ios
  connection: local
  gather_facts: no
  
  tasks:
   - name: show version
     ios_command:
       commands: show version
      register: ver
   - debug:
       msg="{{ ver.stdout_lines }}"
